[[point_light]]
position = [0.0, 5.0, 0.0]
intensity = 400000000.0

# Left sphere
[[sphere]]
position = [-2.0, 2.0, 10.0]
radius = 2.0
material = "Mirror"
colour = [1.0, 1.0, 1.0]

# Right sphere
[[sphere]]
position = [2.0, 2.0, 10.0]
radius = 2.0
material = "Lambertian"
colour = [0.5, 0.5, 0.5]

# Floor
[[plane]]
point = [0.0, 0.0, 0.0]
normal = [0.0, 1.0, 0.0]
material = "Lambertian"
colour = [0.0, 0.0, 1.0]

# Back wall
[[plane]]
colour = [0.0, 1.0, 0.0]
point = [0.0, 0.0, 24.0]
normal = [0.0, 0.0, -1.0]
material = "Lambertian"

# Ceiling
[[plane]]
point = [0.0, 12.0, 0.0]
normal = [0.0, -1.0, 0.0]
material = "Lambertian"
colour = [1.0, 0.0, 0.0]

# Front wall
[[plane]]
point = [0.0, 0.0, -12.0]
normal = [0.0, 0.0, 1.0]
material = "Lambertian"
colour = [1.0, 0.0, 1.0]

# Right wall
[[plane]]
point = [12.0, 0.0, 0.0]
normal = [-1.0, 0.0, 0.0]
material = "Lambertian"
colour = [1.0, 1.0, 0.0]

# Left wall
[[plane]]
point = [-12.0, 0.0, 20.0]
normal = [1.0, 0.0, 0.0]
material = "Lambertian"
colour = [0.0, 1.0, 1.0]
